#!/bin/sh

ln -s ../mlt.i
swig -c++ -I../../melted++ `pkg-config --cflags mlt++-7` -php5 -noproxy mlt.i
g++ -fPIC -DPIC -D_GNU_SOURCE -c -rdynamic -pthread -I../../melted++ `pkg-config --cflags mlt++-7` `php-config --includes` mlt_wrap.cpp
gcc -shared mlt_wrap.o -L../../melted++ -lmelted++ -o mlt.so || exit $?
